// 7 days in milliseconds
export const JWT_REFRESH_TOKEN_EXPIRATION_TIME = 7 * 24 * 60 * 60 * 1000;

export const REQUIRED_ENV_VARS = [
  "JWT_ACCESS_SECRET",
  "JWT_REFRESH_SECRET",
  "JWT_ACCESS_TOKEN_EXPIRATION_TIME",
  "JWT_REFRESH_TOKEN_EXPIRATION_TIME",
  "SMTP_HOST",
  "SMTP_PORT",
  "SMTP_USER",
  "SMTP_PASS",
  "API_URL",
  "CRYPTOCOMPARE_API_KEY",
  "ETHERSCAN_API_KEY",
  "CLIENT_URL",
  "DATABASE_URL",
  "POSTGRES_USER",
  "POSTGRES_PASSWORD",
  "POSTGRES_DB",
  "PORT",
] as const;

export const BCRYPT_SALT_ROUNDS = 10;

export const LOGIN_LIMITER_MAX_REQUESTS = 5;
export const REGISTER_LIMITER_MAX_REQUESTS = 3;
export const AUTH_LIMITER_WINDOW_MS = 15 * 60 * 1000;
